#!/usr/bin/env bash

# winscp env
progName=winscp
progRealPath=$SNAP/usr/share/$progName
progHome=$SNAP_USER_DATA/$progName

if [ ! -d $progHome ];then
ensure_dir_exists $progHome
fi

# Delete broken symlinks
find "$progHome/" -type l -delete &>/dev/null
# Update existing symlinks, add new symlinks
cp -urs "$progRealPath/"* "$progHome" &>/dev/null
